### ISSUE TITLE
Add final sounds to sound manager

### ISSUE THREAD

**Issue by DecJam** [deepfry3/AMAZEing#10]

**Comment by deepfry3** [comment]
Currently working on ball-rolling sounds.
Other sounds needed:
- Button presses/touches
- Gem collection
- Finish
- Potentially more...

**Comment by deepfry3** [comment]
Added ball rolling and colliding under commit 9f104cf. Further sounds still required.

**Comment by deepfry3** [comment]
Gem sound to be quieter. Reintroduce background music very quietly.
